service: geolocation-server

image: luuphuphat69/server

servers:
  web:
    - 161.248.4.185

ssh:
  user: root
  port: 8686  # 👈 Explicitly tell Kamal to use 8686 for SSH

proxy:
  ssl: true
  host: app.geolocation.space

registry:
  username: luuphuphat69
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .
  dockerfile: ./Dockerfile