# fly.toml app configuration file generated for geolocation on 2025-06-08T23:03:23+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geolocation'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
